/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_factorymode_alsps_sensorActivity.h */

#ifndef _Included_com_mediatek_factorymode_OpticalActivity
#define _Included_com_mediatek_factorymode_OpticalActivity
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_mediatek_factorymode_OpticalActivity
 * Method:    opened
 * Signature: ()I
  读取环境光数据CDATA
 */
JNIEXPORT jint JNICALL Java_com_mediatek_factorymode_OpticalActivity_getCdata();

#ifdef __cplusplus
}
#endif
#endif
